node {
  stage('SCM') {
    checkout scm
  }
  
  stage('Build & Test') {
    dir('my-java-app') {
      def mvn = tool 'Maven3';
      sh "${mvn}/bin/mvn clean compile test"
    }
  }
  
  stage('SonarQube Analysis') {
    dir('my-java-app') {
      def mvn = tool 'Maven3';
      withSonarQubeEnv() {
        sh "${mvn}/bin/mvn sonar:sonar -Dsonar.projectKey=My-Java-App -Dsonar.projectName='My Java App'"
      }
    }
  }
  
  stage('Package') {
    dir('my-java-app') {
      def mvn = tool 'Maven3';
      sh "${mvn}/bin/mvn package -DskipTests"
    }
  }
  
  stage('Deploy to Nexus') {
    dir('my-java-app') {
      def mvn = tool 'Maven3';
      sh "${mvn}/bin/mvn deploy -DskipTests"
    }
  }
  
  stage('Archive Artifacts') {
    dir('my-java-app') {
      archiveArtifacts artifacts: 'target/*.jar', fingerprint: true
    }
  }
}
