node {
  stage('SCM') {
    checkout scm
  }
  stage('SonarQube Analysis') {
    // Change to the subdirectory where pom.xml is located
    dir('my-java-app') {
      def mvn = tool 'Maven3';
      withSonarQubeEnv() {
        sh "${mvn}/bin/mvn clean verify sonar:sonar -Dsonar.projectKey=my-java-app -Dsonar.projectName='My Java App'"
      }
    }
  }
}
